CREATE TABLE "PRODUCT" (
	"PRD_NO"	NUMBER		NOT NULL,
	"NAME"	VARCHAR2(50)		NULL,
	"CATEGORY"	VARCHAR2(20)		NULL,
	"PRICE"	NUMBER		NULL,
	"PRD_DESC"	VARCHAR2(300)		NULL,
	"IMAGE"	VARCHAR2(300)		NULL,
	"BRAND"	VARCHAR2(50)		NULL,
	"DISPLAY"	VARCHAR2(1) DEFAULT 'Y',
	"SALE"	VARCHAR2(1) DEFAULT 'Y',
	"STOCK"	NUMBER	DEFAULT 9999	NULL,
	"RGSTR_DATE"	DATE	DEFAULT SYSDATE,
	"TOTAL_SALES"	NUMBER		NULL,
	"VIEWS"	NUMBER		NULL,
	"RATING"	NUMBER(3,2)		NULL,
	"STATUS"	VARCHAR2(1) DEFAULT 'Y'
);

COMMENT ON COLUMN "PRODUCT"."PRD_NO" IS '상품번호';

COMMENT ON COLUMN "PRODUCT"."NAME" IS '상품명';

COMMENT ON COLUMN "PRODUCT"."CATEGORY" IS '카테고리';

COMMENT ON COLUMN "PRODUCT"."PRICE" IS '판매가격';

COMMENT ON COLUMN "PRODUCT"."PRD_DESC" IS '상품설명';

COMMENT ON COLUMN "PRODUCT"."IMAGE" IS '이미지';

COMMENT ON COLUMN "PRODUCT"."BRAND" IS '브랜드';

COMMENT ON COLUMN "PRODUCT"."DISPLAY" IS '진열상태(Y/N)';

COMMENT ON COLUMN "PRODUCT"."SALE" IS '판매상태(Y/N)';

COMMENT ON COLUMN "PRODUCT"."STOCK" IS '재고';

COMMENT ON COLUMN "PRODUCT"."RGSTR_DATE" IS '등록날짜';

COMMENT ON COLUMN "PRODUCT"."TOTAL_SALES" IS '총판매수량';

COMMENT ON COLUMN "PRODUCT"."VIEWS" IS '조회수';

COMMENT ON COLUMN "PRODUCT"."RATING" IS '평점';

COMMENT ON COLUMN "PRODUCT"."STATUS" IS '상태(Y/N)';

CREATE TABLE "MEMBER" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"ID"	VARCHAR2(30)		NULL,
	"PASSWORD"	VARCHAR2(50)		NULL,
	"NAME"	VARCHAR2(20)		NULL,
	"PHONE"	VARCHAR2(20)		NULL,
	"EMAIL"	VARCHAR2(50)		NULL,
	"POSTAL_CODE"	VARCHAR2(20)		NULL,
	"ADDRESS"	VARCHAR2(400)		NULL,
	"ADDRESS_DETAIL"	VARCHAR2(400)		NULL,
	"BIRTH"	VARCHAR2(20)		NULL,
	"ENROLL_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"ROLE"	VARCHAR2(30)	DEFAULT 'ROLL_USER'	NULL,
	"STATUS"	VARCHAR2(1) DEFAULT 'Y' CHECK(STATUS IN('Y', 'N'))
);

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원 번호';

COMMENT ON COLUMN "MEMBER"."ID" IS '아이디';

COMMENT ON COLUMN "MEMBER"."PASSWORD" IS '비밀번호';

COMMENT ON COLUMN "MEMBER"."NAME" IS '이름';

COMMENT ON COLUMN "MEMBER"."PHONE" IS '전화번호';

COMMENT ON COLUMN "MEMBER"."EMAIL" IS '이메일';

COMMENT ON COLUMN "MEMBER"."POSTAL_CODE" IS '우편번호';

COMMENT ON COLUMN "MEMBER"."ADDRESS" IS '주소';

COMMENT ON COLUMN "MEMBER"."ADDRESS_DETAIL" IS '세부주소';

COMMENT ON COLUMN "MEMBER"."BIRTH" IS '생년월일';

COMMENT ON COLUMN "MEMBER"."ENROLL_DATE" IS '가입일자';

COMMENT ON COLUMN "MEMBER"."ROLE" IS '유형(관리자 여부)';

COMMENT ON COLUMN "MEMBER"."STATUS" IS '상태(Y/N)';

CREATE TABLE "ORDER" (
	"ORDER_NO"	NUMBER		NOT NULL,
	"REQUEST"	VARCHAR2(300)		NULL,
	"PAYMENT_METHOD"	VARCHAR2(50)		NULL,
	"PAYMENT"	NUMBER		NULL,
	"SHIP_STATUS"	VARCHAR2(20)		NULL,
	"ORDER_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"CANCLE_STATUS"	VARCHAR2(1) DEFAULT 'N',
	"CANCLE_REASON"	VARCHAR2(50)		NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"SHIP_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "ORDER"."ORDER_NO" IS '주문 번호';

COMMENT ON COLUMN "ORDER"."REQUEST" IS '배송 요청사항';

COMMENT ON COLUMN "ORDER"."PAYMENT_METHOD" IS '결제수단';

COMMENT ON COLUMN "ORDER"."PAYMENT" IS '결제 금액';

COMMENT ON COLUMN "ORDER"."SHIP_STATUS" IS '배송상태';

COMMENT ON COLUMN "ORDER"."ORDER_DATE" IS '주문일';

COMMENT ON COLUMN "ORDER"."CANCLE_STATUS" IS '취소 여부(Y/N)';

COMMENT ON COLUMN "ORDER"."CANCLE_REASON" IS '취소 사유';

COMMENT ON COLUMN "ORDER"."MEMBER_NO" IS '회원 번호';

COMMENT ON COLUMN "ORDER"."SHIP_NO" IS '배송지 번호';

CREATE TABLE "REVIEW" (
	"REVIEW_NO"	NUMBER		NOT NULL,
	"RATED"	NUMBER(2,1)		NULL,
	"NAME"	VARCHAR2(200)		NULL,
	"CONTENT"	VARCHAR2(1500)		NULL,
	"IMAGE"	VARCHAR2(50)		NULL,
	"RGSTR_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"VIEWS"	NUMBER		NULL,
	"STATUS"	VARCHAR2(1) DEFAULT 'Y' CHECK(STATUS IN('Y', 'N')),
	"USER_NO"	NUMBER		NOT NULL,
	"PRD_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "REVIEW"."REVIEW_NO" IS '리뷰 번호';

COMMENT ON COLUMN "REVIEW"."RATED" IS '별점';

COMMENT ON COLUMN "REVIEW"."NAME" IS '리뷰 제목';

COMMENT ON COLUMN "REVIEW"."CONTENT" IS '리뷰 내용';

COMMENT ON COLUMN "REVIEW"."IMAGE" IS '첨부 이미지';

COMMENT ON COLUMN "REVIEW"."RGSTR_DATE" IS '등록 날짜';

COMMENT ON COLUMN "REVIEW"."VIEWS" IS '조회수';

COMMENT ON COLUMN "REVIEW"."STATUS" IS '상태(Y/N)';

COMMENT ON COLUMN "REVIEW"."USER_NO" IS '회원 번호';

COMMENT ON COLUMN "REVIEW"."PRD_NO" IS '상품번호';


CREATE TABLE "SHIPPING_LOCATION" (
	"SHIP_NO"	NUMBER		NOT NULL,
	"SHIP_NAME"	VARCHAR2(50)		NULL,
	"RECIPIENT"	VARCHAR2(30)		NULL,
	"PHONE"	VARCHAR2(20)		NULL,
	"POSTAL_CODE"	VARCHAR2(30)		NULL,
	"SHIP_ADDRESS"	VARCHAR2(200)		NULL,
	"SHIP_ADDRESS_DETAIL"	VARCHAR2(200)		NULL,
	"MOUNTAIN"	VARCHAR2(1) DEFAULT 'Y',
	"PRICE"	NUMBER		NULL,
	"DEFAULT"	VARCHAR2(1) DEFAULT 'Y',
	"STATUS"	VARCHAR2(1) DEFAULT 'Y',
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "SHIPPING_LOCATION"."SHIP_NO" IS '배송지 번호';

COMMENT ON COLUMN "SHIPPING_LOCATION"."SHIP_NAME" IS '배송지명';

COMMENT ON COLUMN "SHIPPING_LOCATION"."RECIPIENT" IS '수취인명';

COMMENT ON COLUMN "SHIPPING_LOCATION"."PHONE" IS '전화번호';

COMMENT ON COLUMN "SHIPPING_LOCATION"."POSTAL_CODE" IS '우편번호';

COMMENT ON COLUMN "SHIPPING_LOCATION"."SHIP_ADDRESS" IS '배송지 주소';

COMMENT ON COLUMN "SHIPPING_LOCATION"."SHIP_ADDRESS_DETAIL" IS '세부주소';

COMMENT ON COLUMN "SHIPPING_LOCATION"."MOUNTAIN" IS '도서산간 지역 여부(Y/N)';

COMMENT ON COLUMN "SHIPPING_LOCATION"."PRICE" IS '배송비';

COMMENT ON COLUMN "SHIPPING_LOCATION"."DEFAULT" IS '기본 배송지 유무(Y/N)';

COMMENT ON COLUMN "SHIPPING_LOCATION"."STATUS" IS '상태(Y/N)';

COMMENT ON COLUMN "SHIPPING_LOCATION"."MEMBER_NO" IS '회원 번호';

CREATE TABLE "SHOPPING_BASKET" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"PAYMENT"	NUMBER		NULL,
	"SHIP_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "SHOPPING_BASKET"."MEMBER_NO" IS '회원 번호';

COMMENT ON COLUMN "SHOPPING_BASKET"."PAYMENT" IS '결제 금액';

COMMENT ON COLUMN "SHOPPING_BASKET"."SHIP_NO" IS '배송지 번호';

CREATE TABLE "ORDER_PRODUCT" (
	"PRD_NO"	NUMBER		NOT NULL,
	"ORDER_NO"	NUMBER		NOT NULL,
	"QUANTITY"	NUMBER		NULL,
	"TOTAL_PRICE"	NUMBER		NULL
);

COMMENT ON COLUMN "ORDER_PRODUCT"."PRD_NO" IS '상품번호';

COMMENT ON COLUMN "ORDER_PRODUCT"."ORDER_NO" IS '주문 번호';

COMMENT ON COLUMN "ORDER_PRODUCT"."QUANTITY" IS '상품 수량';

COMMENT ON COLUMN "ORDER_PRODUCT"."TOTAL_PRICE" IS '상품 총 가격';

CREATE TABLE "SUPPORT" (
	"SUPPORT_NO"	NUMBER		NOT NULL,
	"CATEGORY"	VARCHAR2(20)		NULL,
	"NAME"	VARCHAR2(200)		NULL,
	"CONTENT"	VARCHAR2(1500)		NULL,
	"RGSTR_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"STATUS"	VARCHAR2(1) DEFAULT 'Y' CHECK(STATUS IN('Y', 'N')),
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "SUPPORT"."SUPPORT_NO" IS '게시글 번호';

COMMENT ON COLUMN "SUPPORT"."CATEGORY" IS '카테고리';

COMMENT ON COLUMN "SUPPORT"."NAME" IS '제목';

COMMENT ON COLUMN "SUPPORT"."CONTENT" IS '내용';

COMMENT ON COLUMN "SUPPORT"."RGSTR_DATE" IS '작성일';

COMMENT ON COLUMN "SUPPORT"."STATUS" IS '상태(Y/N)';

COMMENT ON COLUMN "SUPPORT"."MEMBER_NO" IS '회원 번호';

CREATE TABLE "INQUIRY" (
	"INQUIRY_NO"	NUMBER		NOT NULL,
	"NAME"	VARCHAR2(200)		NULL,
	"INQUIRY_CONTENT"	VARCHAR2(1500)		NULL,
	"RGSTR_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"ANSWER_STATE"	VARCHAR2(1) DEFAULT 'N',
	"ANSWER_CONTENT"	VARCHAR2(1500)		NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "INQUIRY"."INQUIRY_NO" IS '게시글 번호';

COMMENT ON COLUMN "INQUIRY"."NAME" IS '제목';

COMMENT ON COLUMN "INQUIRY"."INQUIRY_CONTENT" IS '내용';

COMMENT ON COLUMN "INQUIRY"."RGSTR_DATE" IS '작성일';

COMMENT ON COLUMN "INQUIRY"."ANSWER_STATE" IS '답변 상태(Y/N)';

COMMENT ON COLUMN "INQUIRY"."ANSWER_CONTENT" IS '답변 내용';

COMMENT ON COLUMN "INQUIRY"."MEMBER_NO" IS '회원 번호';

CREATE TABLE "SHOPPING_BASKET_PRODUCT" (
	"PRD_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"QUANTITY"	NUMBER		NULL,
	"TOTAL_PRICE"	NUMBER		NULL
);

COMMENT ON COLUMN "SHOPPING_BASKET_PRODUCT"."PRD_NO" IS '상품번호';

COMMENT ON COLUMN "SHOPPING_BASKET_PRODUCT"."MEMBER_NO" IS '회원 번호';

COMMENT ON COLUMN "SHOPPING_BASKET_PRODUCT"."QUANTITY" IS '상품 수량';

COMMENT ON COLUMN "SHOPPING_BASKET_PRODUCT"."TOTAL_PRICE" IS '상품 총 가격';

ALTER TABLE "PRODUCT" ADD CONSTRAINT "PK_PRODUCT" PRIMARY KEY (
	"PRD_NO"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEMBER_NO"
);

ALTER TABLE "ORDER" ADD CONSTRAINT "PK_ORDER" PRIMARY KEY (
	"ORDER_NO"
);

ALTER TABLE "REVIEW" ADD CONSTRAINT "PK_REVIEW" PRIMARY KEY (
	"REVIEW_NO"
);

ALTER TABLE "SHIPPING_LOCATION" ADD CONSTRAINT "PK_SHIPPING_LOCATION" PRIMARY KEY (
	"SHIP_NO"
);

ALTER TABLE "SHOPPING_BASKET" ADD CONSTRAINT "PK_SHOPPING_BASKET" PRIMARY KEY (
	"MEMBER_NO"
);

ALTER TABLE "ORDER_PRODUCT" ADD CONSTRAINT "PK_ORDER_PRODUCT" PRIMARY KEY (
	"PRD_NO",
	"ORDER_NO"
);

ALTER TABLE "SUPPORT" ADD CONSTRAINT "PK_SUPPORT" PRIMARY KEY (
	"SUPPORT_NO"
);

ALTER TABLE "INQUIRY" ADD CONSTRAINT "PK_INQUIRY" PRIMARY KEY (
	"INQUIRY_NO"
);

ALTER TABLE "SHOPPING_BASKET_PRODUCT" ADD CONSTRAINT "PK_SHOPPING_BASKET_PRODUCT" PRIMARY KEY (
	"PRD_NO",
	"MEMBER_NO"
);

ALTER TABLE "SHOPPING_BASKET" ADD CONSTRAINT "FK_MEMBER_TO_SHOPPING_BASKET_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "ORDER_PRODUCT" ADD CONSTRAINT "FK_PRODUCT_TO_ORDER_PRODUCT_1" FOREIGN KEY (
	"PRD_NO"
)
REFERENCES "PRODUCT" (
	"PRD_NO"
);

ALTER TABLE "ORDER_PRODUCT" ADD CONSTRAINT "FK_ORDER_TO_ORDER_PRODUCT_1" FOREIGN KEY (
	"ORDER_NO"
)
REFERENCES "ORDER" (
	"ORDER_NO"
);

ALTER TABLE "SHOPPING_BASKET_PRODUCT" ADD CONSTRAINT "FK_PRODUCT_TO_SHOPPING_BASKET_PRODUCT_1" FOREIGN KEY (
	"PRD_NO"
)
REFERENCES "PRODUCT" (
	"PRD_NO"
);

ALTER TABLE "SHOPPING_BASKET_PRODUCT" ADD CONSTRAINT "FK_SHOPPING_BASKET_TO_SHOPPING_BASKET_PRODUCT_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "SHOPPING_BASKET" (
	"MEMBER_NO"
);

